language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6


cache:
  directories:
    - $HOME/.cache/pip

services:
  - MySQL
  - PostgreSQL

env:
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: 2.7
      env: DJANGO=2.1
    - python: 2.7
      env: DJANGO=2.2

    - python: 3.4
      env: DJANGO=2.0
    - python: 3.4
      env: DJANGO=2.1
    - python: 3.4
      env: DJANGO=2.2

    - python: 3.6
      env: DJANGO=1.9
    - python: 3.6
      env: DJANGO=1.10

install:
  - pip install tox-travis "coverage<=4.0" codecov

script:
  - tox

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
